[phases.setup]
nixPkgs = [
  "nodejs_20",
  "npm",
  "pkg-config",
  "cairo",
  "pango",
  "libjpeg",
  "giflib",
  "librsvg",
  "pixman",
  "libuuid",
  "python3",
  "make",
  "gcc",
  "glibc"
]

[phases.install]
cmds = ["npm install --build-from-source"]

[start]
cmd = "node index.js"
